name: CI/CD - Mongo

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  deliver:
    runs-on: ubuntu-latest
    env:
      MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -t mongo .
        
      - name: Tags
        run: |
          docker tag mongo ${{ secrets.DOCKER_ORGANIZATION }}/mongo:release-${{ github.sha }}
          docker tag mongo ${{ secrets.DOCKER_ORGANIZATION }}/mongo:latest

      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_ORGANIZATION }}/mongo:release-${{ github.sha }}
          docker push ${{ secrets.DOCKER_ORGANIZATION }}/mongo:latest