name: Release - Mongo - Build and Push to Dockerhub
on:
  push:
    branches:
      - release-*
  pull_request:
    branches:
      - release-*

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -t mongo .
        
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Tag and Push
        run: |
          tag="${{ steps.extract_branch.outputs.branch }}"
          docker tag mongo "${{ secrets.DOCKER_ORGANIZATION }}/mongo:$tag"
          docker push "${{ secrets.DOCKER_ORGANIZATION }}/mongo:$tag"
