name: Test - Mongo - Build and Push to Dockerhub

on:
  push:
    branches:
      - test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -t mongo .
        
      - name: Tag and Push
        run: |
          tag="test-$(date +%s)"
          docker tag mongo "${{ secrets.DOCKER_ORGANIZATION }}/mongo:$tag"
          docker push "${{ secrets.DOCKER_ORGANIZATION }}/mongo:$tag"
